---
title: "Winicius Faquieri"
image: "photo.jfif"
links:
  - label: LinkedIn
    url: "https://www.linkedin.com/in/winicius-faquieri-7b73b0199/"
  - label: Twitter
    url: "https://twitter.com/wfaquieri"
  - label: GitHub
    url: "https://github.com/wfaquieri"
  - label: Email
    url: "wfaquieri@gmail.com"
output:
  postcards::trestles
---

<br>
 
I am a data analyst in the Data Mining team at FGV-IBRE, I have experience in data research and analysis. I have been at FGV since 2017 and have already developed and participated in several projects related to Data Science, Data Analytics and Big Data.

---

# Education:

-Economist (UERJ - State University of Rio de Janeiro)

-Master in Economics (UERJ - State University of Rio de Janeiro)

-Master in Technology in artificial intelligence, machine learning and deep learning (INFNET Institute) - In progress...

---

# Specialties:

-Programming in R, Statistical & Econometrics, SQL, BigQuery, Text Mining, Visualizations, Development of Web applications and Dashboards (using R Shiny library).

---

# Publications

-[Can Gaussian factor models of commodity prices capture the financialization phenomenon?](https://www.sciencedirect.com/science/article/abs/pii/S1062940819300117)

-[Hedging the Brazilian stock index in the era of low interest rates: What has changed?](https://bibliotecadigital.fgv.br/ojs/index.php/rbfin/article/view/81625)

-[Análise do comportamento da volatilidade da taxa de câmbio euro-dolar](https://www.e-publicacoes.uerj.br/index.php/cadest/article/view/27738)

-[Financialização dos mercados futuros de commodities: uma abordagem através do modelo de Schwartz-Smith](https://www.bdtd.uerj.br:8443/handle/1/7653)

-[Financialization of the commodity future markets through factor models (IMPA, Research in Options 2017)](https://impa.br/wp-content/uploads/2017/11/RiO2017-CT_FAiube.pdf)

---
